services:
  rstudio:
    image: researchtools:latest
    container_name: tools
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=rstudio
      - TZ=Asia/Tokyo
      - DISABLE_AUTH=true
      - ROOT=true
    ports:
      - 8787:8787
    volumes:
      - ./.config:/home/rstudio/.config
      - ./.cache:/home/rstudio/.cache
      - ./.TinyTex:/home/rstudio/.TinyTex
      - ./.local:/home/rstudio/.local
      - ./.vscode-server:/home/rstudio/.vscode-server
      - ./other:/home/rstudio/other
      - ./projects:/home/rstudio/projects
    restart: unless-stopped