services:
  rstudio:
    volumes:
      - ./.config:/home/rstudio/.config
      - ./.cache:/home/rstudio/.cache
      - ./.TinyTeX:/home/rstudio/.TinyTeX
      - ./.local:/home/rstudio/.local
      - ./.vscode-server:/home/rstudio/.vscode-server
      - ./other:/home/rstudio/other
      - ./projects:/home/rstudio/projects
    restart: on-failure